---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

name: üîê [R] OpenSSF Scorecard

# yamllint disable-line rule:truthy
on:
  workflow_call:

# Note: https://github.com/ossf/scorecard-action#workflow-restrictions
# This workflow cannot be converted into a composite action

# Declare default permissions as none.
permissions: {}

jobs:
  openssf-scorecard:
    name: "Scan"
    runs-on: ubuntu-24.04
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to publish results and get a badge (see publish_results below).
      id-token: write
      # Uncomment the permissions below if installing in a private repository.
      # contents: read
      # actions: read
    steps:
      - name: "Checkout code"
        # yamllint disable-line rule:line-length
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: "Run analysis"
        # yamllint disable-line rule:line-length
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: "Upload artifact"
        # yamllint disable-line rule:line-length
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5

      # Upload the results to GitHub's code scanning dashboard (optional).
      - name: "Upload to code-scanning"
        # yamllint disable-line rule:line-length
        uses: github/codeql-action/upload-sarif@014f16e7ab1402f30e7c3329d33797e7948572db # 4.31.3
        with:
          sarif_file: results.sarif

  # Summary output MUST be in a separate job
  # (refer to the upstream ossf/scorecard-action documentation)
  summary-output:
    name: "Link"
    needs: openssf-scorecard
    runs-on: ubuntu-24.04
    steps:
      - name: "Provide link to scorecard"
        # The upstream action does not provide any useful summary output
        # the action below adds a hyperlink to the OpenSSF Scorecard/report
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/openssf-scorecard-summary-action@0985db543f90ce527ba6e673f994630a5fcad435 # v0.1.0
