---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on tag push, promotes draft release
name: 'Release on Tag Push ðŸš€'

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      # Triggered only by semantic tags push
      - '**'

permissions: {}

jobs:
  promote-release:
    name: 'Promote Draft Release'
    # yamllint disable-line rule:line-length
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: write
    timeout-minutes: 3
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911  # v2.13.0
        with:
          egress-policy: audit

      # yamllint disable-line rule:line-length
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: 'Verify Pushed Tag'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/tag-push-verify-action@f9c6e753870c6405883be2ba18af05d075aaffe8  # v0.1.0
        with:
          versioning: 'semver'

      - name: 'Promote draft release'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/draft-release-promote-action@d7e7df12e32fa26b28dbc2f18a12766482785399  # v0.1.2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ github.ref_name }}"
          latest: true
